name: fisio_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bubble_bottom_bar: ^1.2.0
  dio: ^3.0.8
  flutter_mobx: ^1.0.1
  mobx: ^1.0.1
  flutter_modular: ^0.4.7+4
  flutter:
    sdk: flutter
  provider: ^4.0.4
  shared_preferences: ^0.5.6
  flutter_speed_dial: ^1.2.5
  flutter_datetime_picker: ^1.3.5
  rich_alert: ^0.1.32
  video_player: ^0.10.9
  animated_splash: ^1.0.0
  page_slider: ^0.0.2
  step_progress_indicator: ^0.2.0+3
  webview_flutter:
    git:
      url: https://github.com/asjqkkkk/plugins.git
      path: packages/webview_flutter
      ref: webview

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.1
  build_runner: ^1.7.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MontserratRegular     
      fonts:
        - asset: fonts/Montserrat_Regular.ttf

    - family: MontserratBold    
      fonts:
        - asset: fonts/Montserrat_Bold.ttf

    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf

  assets:
    - assets/
    - assets/infografico/index.html

    - assets/logo/logo_com_nome_fbranco.png
    - assets/logo/logo_sem_nome_fbranco.png
    - assets/logo/logo_com_nome_ftransparente.png
    - assets/logo/logo_sem_nome_ftransparente.png

    - assets/caps_illustrations/cap1_illustration.png

    - assets/caps_illustrations/cap2_illustration.png
    - assets/caps_illustrations/cap2-01.png
    - assets/caps_illustrations/cap2-02.png

    - assets/caps_illustrations/cap3_illustration.png

    - assets/caps_illustrations/cap4_illustration.png
    - assets/caps_illustrations/cap4-01.png

    - assets/caps_illustrations/cap5_illustration.png
    - assets/caps_illustrations/cap6_illustration.png

    - assets/videos/cap1.mp4
    - assets/videos/cap3.mp4

    - assets/infografico/assets/imgs/basquete.png
    - assets/infografico/assets/imgs/bg.jpg
    - assets/infografico/assets/imgs/celular.png
    - assets/infografico/assets/imgs/corre.png
    - assets/infografico/assets/imgs/ginasta.png
    - assets/infografico/assets/imgs/idosa.png
    - assets/infografico/assets/imgs/info.png
    - assets/infografico/assets/imgs/mapa.png
    - assets/infografico/assets/imgs/movedor.png
    - assets/infografico/assets/imgs/movedor.gif
    - assets/infografico/assets/imgs/posto.png
    - assets/infografico/assets/imgs/team.png
    - assets/infografico/assets/imgs/triste.png
    - assets/infografico/assets/imgs/rosto.png
    